### ISSUE TITLE
Conda install instructions bug out

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdshub.github.io#14]
`conda env create -n myenvname -f /reg/g/pcds/pyps/conda/pcds-envs/pcds.yaml`

Can throw an error if the user doesn't have write permissions in `/reg/g/pcds/pyps/conda/pcds-envs` because it tries to create a temporary file (!!?)

**Comment by ZLLentz** [comment]
Note to self to change these instructions to:
`cp /reg/g/pcds/pyps/conda/pcds-envs/pcds.yaml ~`
`conda env create -n myenvname -f ~/pcds.yaml`

**Comment by ZryletTC** [comment]
I don't have any issue doing this, although I need to use the new path:
`conda env create -n myenvname -f /reg/g/pcds/pyps/conda/pcds-envs/envs/pcds/env.yaml`
which is fixed in #15.

Has this been fixed in the past two years, via a change in directory permissions?

**Comment by ZLLentz** [comment]
Possibly has been fixed, I don't actually know how to recreate this one. I don't remember what event triggered this issue.

**Comment by ZryletTC** [comment]
Can this issue be closed?
Everyone in `ps-pcds` has write access to `/reg/g/pcds/pyps/conda/pcds-envs`. If you think anybody else will be reading the page, I can add the change you noted,
```
cp /reg/g/pcds/pyps/conda/pcds-envs/pcds.yaml ~
conda env create -n myenvname -f ~/pcds.yaml
```
to #15.
