### ISSUE TITLE
Need instructions for making a personal dev build of the greater "hutch-python" API 

### ISSUE THREAD

**Issue by rajanplumley** [pcdshub/pcdshub.github.io#7]
It'd be nice if there were instructions for how to get your own checkouts of pcds modules and databases into a python/hutch-python session for working on development changes.  

i.e. a **maintainable** way to get your modules to talk to each other without hacking your $PATH to pieces.  

For github/conda noobs like myself this is daunting and feels like a barrier for entry to the esteemed development club

**Comment by teddyrendahl** [comment]
😿 but we need all the developers we can get!

Have you taken a look at?
https://pcdshub.github.io/installation.html
https://pcdshub.github.io/development.html

Can you let us know which specific part of the process we are missing or what is unclear?

**Comment by ZLLentz** [comment]
@teddyrendahl We don't have any instructions on how to have your checked-out modules shadow over the conda installed modules. I can add a blurb about $PYTHONPATH and provide some nifty scripts I've been using to keep myself organized.

**Comment by teddyrendahl** [comment]
Ah, using `python setup.py develop` and the like? That is certainly an unintended omission. Might be nice if some of those scripts end up in https://github.com/pcdshub/engineering_tools 😉

**Comment by ZLLentz** [comment]
Needs some clean-up, but sure

**Comment by ZLLentz** [comment]
I don't use `python setup.py develop` btw, it's annoying to manage environments like this. Much easier for me to manipulate $PYTHONPATH

**Comment by teddyrendahl** [comment]
Sure. Also thinking out loud here, it isn't incredibly obvious how to launch a `hutch-python` session with your module patched over. Even if you say, fork the mfx repository all the startup scripts will force you into the released environment. Might be nice to have a little "how-to" on how to launch a full hutch-python session from your development environment.

**Comment by rajanplumley** [comment]
Yep, this is what I’m referring to.  Its not clear how to do work with my
own changes underneath, ya dig?

**Comment by teddyrendahl** [comment]
:spoon:
